version: '3.8'
services:
  app:
    image: esamarathon/rabbithole:2
    build: .
    volumes:
      - ./appsettings.json:/app/appsettings.json:ro
    depends_on:
      - postgres

  db:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=rabbithole