version: '3.8'
services:
  app:
    image: esamarathon/rabbithole:2
    build: .
    volumes:
      - ./appsettings.json:/app/appsettings.json:ro
    depends_on:
      - postgres

  db:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=rabbithole


  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5671:5671"
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=password1
      - RABBITMQ_DEFAULT_VHOST=default